name: Test
on: 
  push:
    branches: [ master ]
jobs:
  test:
    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9"]
        os: ["ubuntu-latest"]
        include:
          - python-version: "3.8"
            os: "macos-latest"
          - python-version: "3.8"
            os: "windows-latest"
        
    steps:
      - name: Checkout
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version}}
      - name: Install dependencies
        run: python -m pip install -U pip
      - name: Run tests
        run: |
          pip install -r requirements.txt
          python -m unittest tests
